version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: TheBestPassword
      POSTGRES_DB: ocso_db
    container_name: ocso_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
